try tests?

diff --git a/.github/workflows/vortex.yml b/.github/workflows/vortex.yml
--- a/.github/workflows/vortex.yml
+++ b/.github/workflows/vortex.yml
@@ -149,15 +149,15 @@ jobs:
 
               ./configure --tooldir=$APPTAINER_TOOLDIR --xlen=${{ matrix.xlen }}
 
-              # mkdir -p build${{ matrix.xlen }}
-              # pushd build${{ matrix.xlen }}
+              mkdir -p build${{ matrix.xlen }}
+              pushd build${{ matrix.xlen }}
               
-              # ../configure --tooldir=$TOOLDIR --xlen=${{ matrix.xlen }}
+              ../configure --tooldir=$TOOLDIR --xlen=${{ matrix.xlen }}
               
-              # source ../ci/toolchain_env.sh
+              source ../ci/toolchain_env.sh
               
-              # make software -s
-              # make tests -s
+              make software -s
+              make tests -s
               
               # popd
           EOF
@@ -167,77 +167,128 @@ jobs:
         with:
           name: build-${{ matrix.os }}-${{ matrix.xlen }}
           path: build${{ matrix.xlen }}
+  test:
+    needs: [container, build]
+    runs-on: ubuntu-22.04
 
-  # test:
-  #   needs: [build]
-  #   strategy:
-  #     matrix:
-  #       os: [ubuntu-22.04, ubuntu-24.04]
-  #       name: [regression]
-  #       xlen: [32]
-  #   env:
-  #       APPTAINER_VERSION: "1.4.3"
-  #   runs-on: ubuntu-22.04
-    
-  #   steps:
-  #     - name: Checkout Code
-  #       uses: actions/checkout@v4
-  #       with:
-  #         submodules: recursive
+    strategy:
+      matrix:
+        os: [ubuntu-22.04, ubuntu-24.04]
+        xlen: [32]
+        name: [kernel]
 
-  #     - name: Install Apptainer
-  #       uses: eWaterCycle/setup-apptainer@v2
-  #       with:
-  #         apptainer-version: ${{ env.APPTAINER_VERSION }}
+    env:
+      APPTAINER_VERSION: "1.4.3"
 
-  #     - name: Download Container Artifact
-  #       uses: actions/download-artifact@v4
-  #       with:
-  #         name: vortex-sif
-  #         path: miscs/apptainer/
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
 
-  #     - name: Download Build Artifacts
-  #       uses: actions/download-artifact@v4
-  #       with:
-  #         name: build-${{ matrix.os }}-${{ matrix.xlen }}
-  #         path: build${{ matrix.xlen }}
+      - name: Install Apptainer
+        uses: eWaterCycle/setup-apptainer@v2
+        with:
+          apptainer-version: ${{ env.APPTAINER_VERSION }}
 
-  #     # - name: interactive debugging
-  #     #   uses: mxschmitt/action-tmate@v3
-  #     #   with:
-  #     #     detached: false
+      - name: Download Container Artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: vortex-sif
+          path: miscs/apptainer/
 
-      # todo: add install two deps from cache
+      - name: Access Toolchain Cache
+        id: cache-toolchain
+        uses: actions/cache@v4
+        with:
+          path: tools
+          key: toolchain-${{ matrix.os }}-${{ hashFiles('ci/toolchain_install.sh') }}
+          restore-keys: |
+            toolchain-${{ matrix.os }}-
 
-          
+      - name: Build Toolchain On Miss
+        if: steps.cache-toolchain.outputs.cache-hit != 'true'
+        run: |
+          echo "Cache miss: building toolchain..."
+          mkdir -p build
+          cd build
+          ../configure --tooldir=${{ github.workspace }}/tools
+          ci/toolchain_install.sh --all
 
-      # - name: Run Tests In Apptainer
-      #   run: |
-      #     apptainer exec \
-      #       --bind ${{ github.workspace }}:${{ github.workspace }} \
-      #       --bind ${{ github.workspace }}/tools:/tools \
-      #       --bind ${{ github.workspace }}/third_party:${{ github.workspace }}/third_party \
-      #       --pwd ${{ github.workspace }} \
-      #       --env TOOLDIR=/tools \
-      #       miscs/apptainer/vortex.sif bash <<'EOF'
-      #         set -e
-      #         pushd build${{ matrix.xlen }}
-      #         source ci/toolchain_env.sh
-      #         chmod -R +x .
-      #         if [ "${{ matrix.name }}" == "regression" ]; then
-      #           ./ci/regression.sh --unittest
-      #           ./ci/regression.sh --isa
-      #           ./ci/regression.sh --kernel
-      #           ./ci/regression.sh --regression
-      #         else
-      #           ./ci/regression.sh --${{ matrix.name }}
-      #         fi
-      #         popd
-      #     EOF
+      - name: Save Updated Toolchain Cache
+        if: steps.cache-toolchain.outputs.cache-hit != 'true'
+        uses: actions/cache/save@v4
+        with:
+          path: tools
+          key: toolchain-${{ matrix.os }}-${{ hashFiles('ci/toolchain_install.sh') }}
+
+      - name: Access Third Party Cache
+        id: cache-thirdparty
+        uses: actions/cache@v4
+        with:
+          path: third_party
+          key: ${{ matrix.os }}-thirdparty-v0.1
+          restore-keys: |
+            ${{ matrix.os }}-thirdparty-
+
+      - name: Build Third Party On Miss
+        if: steps.cache-thirdparty.outputs.cache-hit != 'true'
+        run: |
+          make -C third_party > /dev/null
+
+      - name: Save Updated Third Party Cache
+        if: steps.cache-thirdparty.outputs.cache-hit != 'true'
+        uses: actions/cache/save@v4
+        with:
+          path: third_party
+          key: ${{ matrix.os }}-thirdparty-v0.1
+
+      - name: Download Build Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: build-${{ matrix.os }}-${{ matrix.xlen }}
+          path: build${{ matrix.xlen }}
+
+      - name: Run Build In Apptainer
+        run: |
+          apptainer exec \
+            --bind ${{ github.workspace }}:${{ github.workspace }} \
+            --bind ${{ github.workspace }}/tools:/tools \
+            --bind ${{ github.workspace }}/third_party:${{ github.workspace }}/third_party \
+            --pwd ${{ github.workspace }} \
+            --env APPTAINER_TOOLDIR=/tools \
+            miscs/apptainer/vortex.sif bash <<'EOF'
+              set -e
+
+              echo "--- what is my tooldir? ---"
+              echo $APPTAINER_TOOLDIR
+
+              echo "--- what is in my tooldir? ---"
+              ls $APPTAINER_TOOLDIR
+
+              echo "can we find ccache?"
+              which ccache || echo "ccache not found"
+
+              echo "is verilator alive?"
+              which verilator || echo "no verilator o.0"
+
+              pushd build${{ matrix.xlen }}
+              source ci/toolchain_env.sh
+              chmod -R +x .
+              if [ "${{ matrix.name }}" == "regression" ]; then
+                ./ci/regression.sh --unittest
+                ./ci/regression.sh --isa
+                ./ci/regression.sh --kernel
+                ./ci/regression.sh --regression
+              else
+                ./ci/regression.sh --${{ matrix.name }}
+              fi
+              popd
+          EOF
 
   complete:
     runs-on: ubuntu-22.04
-    needs: [build]
+    needs: [test]
     steps:
       - name: Check Completion
         run: echo "All container, build, and test jobs passed successfully."
